/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nx-netsim-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nx-netsim-cli.yang */
public class tailfNedIdCiscoNxNetsimCli extends ConfNamespace {

    public static final long serialVersionUID = 454614720L;

    public static final int hash = 454614720;
    public int hash() {
        return tailfNedIdCiscoNxNetsimCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nx-netsim-cli";
    public String id() {
        return tailfNedIdCiscoNxNetsimCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nx-netsim-cli";
    public String uri() {
        return tailfNedIdCiscoNxNetsimCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNxNetsimCli.uri);
    }

    public static final String prefix = "cisco-nx-netsim-cli";
    public String prefix() {
        return tailfNedIdCiscoNxNetsimCli.prefix;
    }

    public tailfNedIdCiscoNxNetsimCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nx_netsim_cli = 445395220;
    public static final String _cisco_nx_netsim_cli_ = "cisco-nx-netsim-cli";
}
