/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-alu-sr-netsim-cli-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-alu-sr-netsim-cli-1.0.yang */
public class tailfNedIdAluSrNetsimCli1_0 extends ConfNamespace {

    public static final long serialVersionUID = 834245947L;

    public static final int hash = 834245947;
    public int hash() {
        return tailfNedIdAluSrNetsimCli1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/alu-sr-netsim-cli-1.0";
    public String id() {
        return tailfNedIdAluSrNetsimCli1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/alu-sr-netsim-cli-1.0";
    public String uri() {
        return tailfNedIdAluSrNetsimCli1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdAluSrNetsimCli1_0.uri);
    }

    public static final String prefix = "alu-sr-netsim-cli-1.0";
    public String prefix() {
        return tailfNedIdAluSrNetsimCli1_0.prefix;
    }

    public tailfNedIdAluSrNetsimCli1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _alu_sr_netsim_cli_10x2e0 = 400494590;
    public static final String _alu_sr_netsim_cli_10x2e0_ = "alu-sr-netsim-cli-1.0";
}
