/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-alu-sr-netsim-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-alu-sr-netsim-cli.yang */
public class tailfNedIdAluSrNetsimCli extends ConfNamespace {

    public static final long serialVersionUID = 281534403L;

    public static final int hash = 281534403;
    public int hash() {
        return tailfNedIdAluSrNetsimCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/alu-sr-netsim-cli";
    public String id() {
        return tailfNedIdAluSrNetsimCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/alu-sr-netsim-cli";
    public String uri() {
        return tailfNedIdAluSrNetsimCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdAluSrNetsimCli.uri);
    }

    public static final String prefix = "alu-sr-netsim-cli";
    public String prefix() {
        return tailfNedIdAluSrNetsimCli.prefix;
    }

    public tailfNedIdAluSrNetsimCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _alu_sr_netsim_cli = 982597716;
    public static final String _alu_sr_netsim_cli_ = "alu-sr-netsim-cli";
}
