/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-asa-netsim-cli-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-asa-netsim-cli-1.0.yang */
public class tailfNedIdCiscoAsaNetsimCli1_0 extends ConfNamespace {

    public static final long serialVersionUID = 1013731109L;

    public static final int hash = 1013731109;
    public int hash() {
        return tailfNedIdCiscoAsaNetsimCli1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-asa-netsim-cli-1.0";
    public String id() {
        return tailfNedIdCiscoAsaNetsimCli1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-asa-netsim-cli-1.0";
    public String uri() {
        return tailfNedIdCiscoAsaNetsimCli1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoAsaNetsimCli1_0.uri);
    }

    public static final String prefix = "cisco-asa-netsim-cli-1.0";
    public String prefix() {
        return tailfNedIdCiscoAsaNetsimCli1_0.prefix;
    }

    public tailfNedIdCiscoAsaNetsimCli1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_asa_netsim_cli_10x2e0 = 18507957;
    public static final String _cisco_asa_netsim_cli_10x2e0_ = "cisco-asa-netsim-cli-1.0";
}
