/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-asa-netsim-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-asa-netsim-cli.yang */
public class tailfNedIdCiscoAsaNetsimCli extends ConfNamespace {

    public static final long serialVersionUID = 796429272L;

    public static final int hash = 796429272;
    public int hash() {
        return tailfNedIdCiscoAsaNetsimCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-asa-netsim-cli";
    public String id() {
        return tailfNedIdCiscoAsaNetsimCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-asa-netsim-cli";
    public String uri() {
        return tailfNedIdCiscoAsaNetsimCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoAsaNetsimCli.uri);
    }

    public static final String prefix = "cisco-asa-netsim-cli";
    public String prefix() {
        return tailfNedIdCiscoAsaNetsimCli.prefix;
    }

    public tailfNedIdCiscoAsaNetsimCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_asa_netsim_cli = 1807639340;
    public static final String _cisco_asa_netsim_cli_ = "cisco-asa-netsim-cli";
}
