/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-router-nc-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.examples.router.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-router-nc-1.0.yang */
public class tailfNedIdRouterNc1_0 extends ConfNamespace {

    public static final long serialVersionUID = 1072025449L;

    public static final int hash = 1072025449;
    public int hash() {
        return tailfNedIdRouterNc1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/router-nc-1.0";
    public String id() {
        return tailfNedIdRouterNc1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/router-nc-1.0";
    public String uri() {
        return tailfNedIdRouterNc1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdRouterNc1_0.uri);
    }

    public static final String prefix = "router-nc-1.0";
    public String prefix() {
        return tailfNedIdRouterNc1_0.prefix;
    }

    public tailfNedIdRouterNc1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _router_nc_10x2e0 = 2088564855;
    public static final String _router_nc_10x2e0_ = "router-nc-1.0";
}
