/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-router-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.examples.router.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-router-nc.yang */
public class tailfNedIdRouterNc extends ConfNamespace {

    public static final long serialVersionUID = 51504667L;

    public static final int hash = 51504667;
    public int hash() {
        return tailfNedIdRouterNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/router-nc";
    public String id() {
        return tailfNedIdRouterNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/router-nc";
    public String uri() {
        return tailfNedIdRouterNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdRouterNc.uri);
    }

    public static final String prefix = "router-nc";
    public String prefix() {
        return tailfNedIdRouterNc.prefix;
    }

    public tailfNedIdRouterNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _router_nc = 841716425;
    public static final String _router_nc_ = "router-nc";
    public static final int    ned_id = 841716425;
    public static final String ned_id_ = "router-nc:router-nc";
}
