#!/bin/sh
# Copyright 2026 Cisco Systems, Inc.
# SPDX-License-Identifier: MIT

BASE=$(cd "$(dirname "$0")" && pwd)
. "$BASE"/util/ca.sh


usage()
{
    cat <<EOF
usage: init-new-ca [label]

    Generate a new self-signed (private) Certificate Authority.

    If an identification label is specified, it is included in the CA name.
    Otherwise, a random label is generated.
EOF
    exit "${1:-0}"
}


show_usage_maybe "$@"
create_ca "$@"
