#!/bin/sh
# Copyright 2026 Cisco Systems, Inc.
# SPDX-License-Identifier: MIT

BASE=$(cd "$(dirname "$0")" && pwd)
. "$BASE"/util/ca.sh


usage()
{
    cat <<EOF
usage: revoke-cert <cert-name>

    Revoke the specified TLS certificate and generate the CRL.

    In case multiple CAs are available, selects the most-recently-created
    CA unless NCSCERT_CAPATH is used to select a specific CA.
EOF
    exit "${1:-0}"
}

with_cert_do revoke_cert "$@"
