/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-router-cli-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-router-cli-1.0.yang */
public class tailfNedIdRouterCli1_0 extends ConfNamespace {

    public static final long serialVersionUID = 1112333253L;

    public static final int hash = 1112333253;
    public int hash() {
        return tailfNedIdRouterCli1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/router-cli-1.0";
    public String id() {
        return tailfNedIdRouterCli1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/router-cli-1.0";
    public String uri() {
        return tailfNedIdRouterCli1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdRouterCli1_0.uri);
    }

    public static final String prefix = "router-cli-1.0";
    public String prefix() {
        return tailfNedIdRouterCli1_0.prefix;
    }

    public tailfNedIdRouterCli1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _router_cli_10x2e0 = 1648164657;
    public static final String _router_cli_10x2e0_ = "router-cli-1.0";
}
