/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-router-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-router-cli.yang */
public class tailfNedIdRouterCli extends ConfNamespace {

    public static final long serialVersionUID = 422824039L;

    public static final int hash = 422824039;
    public int hash() {
        return tailfNedIdRouterCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/router-cli";
    public String id() {
        return tailfNedIdRouterCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/router-cli";
    public String uri() {
        return tailfNedIdRouterCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdRouterCli.uri);
    }

    public static final String prefix = "router-cli";
    public String prefix() {
        return tailfNedIdRouterCli.prefix;
    }

    public tailfNedIdRouterCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _router_cli = 1116521456;
    public static final String _router_cli_ = "router-cli";
}
