/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/netsim-ned-a10-acos-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module netsim-ned-a10-acos-stats.yang */
public class netsimNedA10AcosStats extends ConfNamespace {

    public static final long serialVersionUID = 1641297154L;

    public static final int hash = 1641297154;
    public int hash() {
        return netsimNedA10AcosStats.hash;
    }

    public static final String id = "_a10-acos-netsim-cli-1.0:a10-acos-netsim-cli-1.0#http://tail-f.com/ned/a10-acos-stats";
    public String id() {
        return netsimNedA10AcosStats.id;
    }

    public static final String uri = "_a10-acos-netsim-cli-1.0:a10-acos-netsim-cli-1.0#http://tail-f.com/ned/a10-acos-stats";
    public String uri() {
        return netsimNedA10AcosStats.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(netsimNedA10AcosStats.uri);
    }

    public static final String prefix = "a10-acos-stats";
    public String prefix() {
        return netsimNedA10AcosStats.prefix;
    }

    public netsimNedA10AcosStats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _exec = 1716494663;
    public static final String _exec_ = "exec";
}
