/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-a10-acos-netsim-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-a10-acos-netsim-cli.yang */
public class tailfNedIdA10AcosNetsimCli extends ConfNamespace {

    public static final long serialVersionUID = 832039569L;

    public static final int hash = 832039569;
    public int hash() {
        return tailfNedIdA10AcosNetsimCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/a10-acos-netsim-cli";
    public String id() {
        return tailfNedIdA10AcosNetsimCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/a10-acos-netsim-cli";
    public String uri() {
        return tailfNedIdA10AcosNetsimCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdA10AcosNetsimCli.uri);
    }

    public static final String prefix = "a10-acos-netsim-cli";
    public String prefix() {
        return tailfNedIdA10AcosNetsimCli.prefix;
    }

    public tailfNedIdA10AcosNetsimCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _a10_acos_netsim_cli = 1200817282;
    public static final String _a10_acos_netsim_cli_ = "a10-acos-netsim-cli";
}
