/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-a10-acos-netsim-cli-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-a10-acos-netsim-cli-1.0.yang */
public class tailfNedIdA10AcosNetsimCli1_0 extends ConfNamespace {

    public static final long serialVersionUID = 250723921L;

    public static final int hash = 250723921;
    public int hash() {
        return tailfNedIdA10AcosNetsimCli1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/a10-acos-netsim-cli-1.0";
    public String id() {
        return tailfNedIdA10AcosNetsimCli1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/a10-acos-netsim-cli-1.0";
    public String uri() {
        return tailfNedIdA10AcosNetsimCli1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdA10AcosNetsimCli1_0.uri);
    }

    public static final String prefix = "a10-acos-netsim-cli-1.0";
    public String prefix() {
        return tailfNedIdA10AcosNetsimCli1_0.prefix;
    }

    public tailfNedIdA10AcosNetsimCli1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _a10_acos_netsim_cli_10x2e0 = 1992592062;
    public static final String _a10_acos_netsim_cli_10x2e0_ = "a10-acos-netsim-cli-1.0";
}
