/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/router-config.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimgen.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module router-config.yang */
public class routerConfig extends ConfNamespace {

    public static final long serialVersionUID = 1910680097L;

    public static final int hash = 1910680097;
    public int hash() {
        return routerConfig.hash;
    }

    public static final String id = "_router-gen-1.0:router-gen-1.0#http://example.com/router-config";
    public String id() {
        return routerConfig.id;
    }

    public static final String uri = "_router-gen-1.0:router-gen-1.0#http://example.com/router-config";
    public String uri() {
        return routerConfig.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(routerConfig.uri);
    }

    public static final String prefix = "sc";
    public String prefix() {
        return routerConfig.prefix;
    }

    public routerConfig() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _trans_id_mode = 430789013;
    public static final String _trans_id_mode_ = "trans-id-mode";
    public static final int    _want_reverse = 1843511563;
    public static final String _want_reverse_ = "want-reverse";
    public static final int    _router_config = 1589374014;
    public static final String _router_config_ = "router-config";
}
