/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-router-gen.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimgen.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-router-gen.yang */
public class tailfNedIdRouterGen extends ConfNamespace {

    public static final long serialVersionUID = 573580500L;

    public static final int hash = 573580500;
    public int hash() {
        return tailfNedIdRouterGen.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/router-gen";
    public String id() {
        return tailfNedIdRouterGen.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/router-gen";
    public String uri() {
        return tailfNedIdRouterGen.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdRouterGen.uri);
    }

    public static final String prefix = "router-gen";
    public String prefix() {
        return tailfNedIdRouterGen.prefix;
    }

    public tailfNedIdRouterGen() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _router_gen = 348882872;
    public static final String _router_gen_ = "router-gen";
}
