/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-router-gen-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimgen.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-router-gen-1.0.yang */
public class tailfNedIdRouterGen1_0 extends ConfNamespace {

    public static final long serialVersionUID = 1985640982L;

    public static final int hash = 1985640982;
    public int hash() {
        return tailfNedIdRouterGen1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/router-gen-1.0";
    public String id() {
        return tailfNedIdRouterGen1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/router-gen-1.0";
    public String uri() {
        return tailfNedIdRouterGen1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdRouterGen1_0.uri);
    }

    public static final String prefix = "router-gen-1.0";
    public String prefix() {
        return tailfNedIdRouterGen1_0.prefix;
    }

    public tailfNedIdRouterGen1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _router_gen_10x2e0 = 1620949329;
    public static final String _router_gen_10x2e0_ = "router-gen-1.0";
}
