/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-iosxr-netsim-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-iosxr-netsim-cli.yang */
public class tailfNedIdCiscoIosxrNetsimCli extends ConfNamespace {

    public static final long serialVersionUID = 1326230643L;

    public static final int hash = 1326230643;
    public int hash() {
        return tailfNedIdCiscoIosxrNetsimCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-iosxr-netsim-cli";
    public String id() {
        return tailfNedIdCiscoIosxrNetsimCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-iosxr-netsim-cli";
    public String uri() {
        return tailfNedIdCiscoIosxrNetsimCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoIosxrNetsimCli.uri);
    }

    public static final String prefix = "cisco-iosxr-netsim-cli";
    public String prefix() {
        return tailfNedIdCiscoIosxrNetsimCli.prefix;
    }

    public tailfNedIdCiscoIosxrNetsimCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_iosxr_netsim_cli = 1666635182;
    public static final String _cisco_iosxr_netsim_cli_ = "cisco-iosxr-netsim-cli";
}
