/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-ios-netsim-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-ios-netsim-cli.yang */
public class tailfNedIdCiscoIosNetsimCli extends ConfNamespace {

    public static final long serialVersionUID = 202222140L;

    public static final int hash = 202222140;
    public int hash() {
        return tailfNedIdCiscoIosNetsimCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-ios-netsim-cli";
    public String id() {
        return tailfNedIdCiscoIosNetsimCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-ios-netsim-cli";
    public String uri() {
        return tailfNedIdCiscoIosNetsimCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoIosNetsimCli.uri);
    }

    public static final String prefix = "cisco-ios-netsim-cli";
    public String prefix() {
        return tailfNedIdCiscoIosNetsimCli.prefix;
    }

    public tailfNedIdCiscoIosNetsimCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_ios_netsim_cli = 441927508;
    public static final String _cisco_ios_netsim_cli_ = "cisco-ios-netsim-cli";
}
