/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-ios-netsim-cli-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-ios-netsim-cli-1.0.yang */
public class tailfNedIdCiscoIosNetsimCli1_0 extends ConfNamespace {

    public static final long serialVersionUID = 629570068L;

    public static final int hash = 629570068;
    public int hash() {
        return tailfNedIdCiscoIosNetsimCli1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-ios-netsim-cli-1.0";
    public String id() {
        return tailfNedIdCiscoIosNetsimCli1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-ios-netsim-cli-1.0";
    public String uri() {
        return tailfNedIdCiscoIosNetsimCli1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoIosNetsimCli1_0.uri);
    }

    public static final String prefix = "cisco-ios-netsim-cli-1.0";
    public String prefix() {
        return tailfNedIdCiscoIosNetsimCli1_0.prefix;
    }

    public tailfNedIdCiscoIosNetsimCli1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_ios_netsim_cli_10x2e0 = 1196682664;
    public static final String _cisco_ios_netsim_cli_10x2e0_ = "cisco-ios-netsim-cli-1.0";
}
