/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-dell-ftos-netsim-cli.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-dell-ftos-netsim-cli.yang */
public class tailfNedIdDellFtosNetsimCli extends ConfNamespace {

    public static final long serialVersionUID = 935659529L;

    public static final int hash = 935659529;
    public int hash() {
        return tailfNedIdDellFtosNetsimCli.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/dell-ftos-netsim-cli";
    public String id() {
        return tailfNedIdDellFtosNetsimCli.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/dell-ftos-netsim-cli";
    public String uri() {
        return tailfNedIdDellFtosNetsimCli.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdDellFtosNetsimCli.uri);
    }

    public static final String prefix = "dell-ftos-netsim-cli";
    public String prefix() {
        return tailfNedIdDellFtosNetsimCli.prefix;
    }

    public tailfNedIdDellFtosNetsimCli() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _dell_ftos_netsim_cli = 521869825;
    public static final String _dell_ftos_netsim_cli_ = "dell-ftos-netsim-cli";
}
