/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-dell-ftos-netsim-cli-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.netsimcli.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-dell-ftos-netsim-cli-1.0.yang */
public class tailfNedIdDellFtosNetsimCli1_0 extends ConfNamespace {

    public static final long serialVersionUID = 1978615731L;

    public static final int hash = 1978615731;
    public int hash() {
        return tailfNedIdDellFtosNetsimCli1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/dell-ftos-netsim-cli-1.0";
    public String id() {
        return tailfNedIdDellFtosNetsimCli1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/dell-ftos-netsim-cli-1.0";
    public String uri() {
        return tailfNedIdDellFtosNetsimCli1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdDellFtosNetsimCli1_0.uri);
    }

    public static final String prefix = "dell-ftos-netsim-cli-1.0";
    public String prefix() {
        return tailfNedIdDellFtosNetsimCli1_0.prefix;
    }

    public tailfNedIdDellFtosNetsimCli1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _dell_ftos_netsim_cli_10x2e0 = 1160673427;
    public static final String _dell_ftos_netsim_cli_10x2e0_ = "dell-ftos-netsim-cli-1.0";
}
